### ISSUE TITLE
General inquiry: Are there any docs which cover building and running the platform

### ISSUE THREAD

**Issue by myFree** [sequenceplanner/sp-rust#3]
Hi; please point me in the right direction if there is a better place for this, as it's just a general inquiry, not a code issue.

Is https://reader.elsevier.com/reader/sd/pii/S2405896317309047?token=61EF180F9A9DFDF45A1370A6998BA13A700F478A7303C1C6C015872B5F3C8BB280171A6030E505BF7D11AB75EE5F470E still a reasonable overview of the functionality Sequence Planner offers?

Are there any docs which cover building and running the platform?
Is the platform relatively mature; or are there still a number of parts which are a work-in-progress?

I'm not planning on putting it into production or anything; just came across the project and am interested in finding out a little bit more.

**Comment by m-dahl** [comment]
Hi,

thanks for reaching out! I would say that the paper you linked still describe the main idea of working with operations in Sequence Planner, however, lately more focus has been more on on-line planning and control of automation systems using ROS as a middle-ware for control. We have recently written a chapter for the upcoming ROS-book (https://www.springer.com/gp/book/9783030459550) which perhaps give a better representation of the focus for Sequence Planner today. The aim is to have a few runnable examples finished when the book lands (e.g. https://github.com/sequenceplanner/dorna_example). While the core ideas of SP are quite mature, this repo is still very much in flux, the port to rust is ongoing and documentation is sorely missing.

I will leave this issue open and write a comment once the book chapter with examples is published.

**Comment by kristoferB** [comment]
The book chapter is now available online: https://link.springer.com/chapter/10.1007/978-3-030-45956-7_1

We hope to have a first version of the tutorials and documentation ready during the autumn.

**Comment by kristoferB** [comment]
Will update to async api and write documentation based on that
